### ISSUE TITLE
review episode markdown

### ISSUE THREAD

**Issue by annefou** [carpentries-incubator/jekyll-pages-novice#113]
- In this episode, we often forget to explicitly mention that learners should click on the **commit changes** button to save permanently. I mean we say they can do it but at least in the first code along, we should tell them to do it (as this is what the image shows: again it is mostly useful for self learners or instructors).

I would add someting like:

Do not forget to click on the **commit changes** button to make sure we permanently save our changes.

- In the paragraph on web links "Linking other websites...) i.e. before exercise **Links**, I think we should explain a bit more how to generate links in markdown (we only explain <>) and do not talk about where to write text ( [ ] ) and where to specify the target ( ( ) ). I would suggest to show how to use [ ] and () for creating web link in markdown and reference. Otherwise the exercise is not feasible for a novice.

**Comment by unode** [comment]
- The screenshots generated in "Syntax Highlighting" are done from the carpentry lesson template instead of GitHub. This can be confusing since we used GitHub everywhere else.
- "Vanilla text" - was not familiar with this expression. It's also used in the exercise screenshot so any change needs to be synced.
- The section on "Bare URLs" is also jekyll specific. On GitHub all text recognized as a URL is automatically made into a link. I wasn't aware of the `< >` syntax for bare URLs.

**Comment by tobyhodges** [comment]
@annefou could you check this, #114, and #115 to see if any can be closed please?

**Comment by annefou** [comment]
close as review has been done.
