### ISSUE TITLE
Write Instructor Notes

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/jekyll-pages-novice#120]
- [x] Specify when co-teaching to only have one instructor repo and invite the other instructors
 - [x] Add advice on where to live demo HTML in the Introduction e.g. CodiMD renders HTML, so could be a good choice
 - [x] Add advice on how to present exercises to learners - (google)slides, copy/paste into etherpad/codimd, share lesson page, other
 - [ ] ~Add the following specifically for the GitHub Pages episode: avoid using reference-style link when first linking between pages on the site. Learners were confused about the difference between `[link text][about]` and `[link text](about)`~

[From Nov 11 pilot notes](https://codimd.carpentries.org/KyHEeesgS7mXKjwwvmHcrw)

**Comment by unode** [comment]
:+1: for CodiMD

Do we want to explore [GitHub classroom](https://education.github.com/)?

Should we also omit `< >` for bare URLs or was that syntax clear for learners?

**Comment by tobyhodges** [comment]
I think the last point is obsolete since we changed the Markdown episode.
Re: presenting exercises to learners. I'm uncomfortable making a clear recommendation on this - different instructors will have different preferences for how to deliver exercises to learners. Suggestions very welcome for what, if anything, to add to #160 on this.

**Comment by sstevens2** [comment]
Closing as I think these are actually all completed with the addition of #160

**Comment by sstevens2** [comment]
oops didn't see that #160 was not yet merged, I'll let this wait until that one is closed
