### ISSUE TITLE
Read through to make language consistent

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/jekyll-pages-novice#124]
Sometimes we use "I" and other times we  use "we".  Should try to standardize the whole lesson to make it consistent.

**Comment by sysilviakim** [comment]
I would like to assist in resolving this issue by creating a pull request. I am guessing that the resolution desired is to switch to "we" in all cases?

**Comment by tobyhodges** [comment]
Thanks @sysilviakim 🙌 Yes I think "we" should be the standard. If you find any cases that you think need more discussion, please post back here. We will look out for your the pull request!

**Comment by sysilviakim** [comment]
@sstevens2 @tobyhodges I'm confused and sitting here scratching my head, because I combed through almost all files in the repository (as well as the actual https://carpentries-incubator.github.io/jekyll-pages-novice/index.html pages themselves) and could not quite find any cases of "I", except for lesson "questions." 

Did you mean to change lesson overview questions such as "How can I write content for my webpages?" to "How can we write content for our webpages?" Let me know if I am missing something.

**Comment by tobyhodges** [comment]
Thanks for taking the time to look into this, @sysilviakim. Indeed it looks like the issue has largely been addressed while we were making other changes to the lesson. I believe the first-person is appropriate for the Questions, so I would prefer that you do not change those. 

That leaves only one place that I could identify where the wording still needs to change: in  [the source file of the _More on Markdown_ Extra page](https://github.com/carpentries-incubator/jekyll-pages-novice/blob/gh-pages/_extras/more_markdown.md), the Key Points include "I recommend writing Markdown links 'reference-style'." That wording needs to be updated to "we" **and** the page layout should be changed to `episode` so these points show up on the website.

If you can spare more time to help us out, and would like to submit a PR fixing that point and specifying the layout for that page, that would be great! The layout can be specified in the YAML header (where the Key Points are defined), by adding `layout: episode`.
