### ISSUE TITLE
Bold text not rendering for me when viewing pages from GitHub not locally

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#142]
See the word "bold" in the pic below.

![image](https://user-images.githubusercontent.com/631719/100210659-23628a80-2f03-11eb-9434-d10923542b45.png)

**Comment by unode** [comment]
Works here both via GitPod and the GitHub version.

![screenshot_2020-11-25_11-55-56_685077352](https://user-images.githubusercontent.com/122319/100218739-6c233f00-2f15-11eb-904b-d08a5674962d.png)

Does it change if you change the zoom level of the page or use a different browser?

**Comment by unode** [comment]
Check also (inspect element) if the HTML is correct. If it's a browser glitch I'm not sure what we could do to workaround.

**Comment by sstevens2** [comment]
I think this might be something with the display in chrome.  May be due to zoom level and surrounding styled text.  After looking at various zoom levels in my chrome, now the screenshot from @anenadic looks very slightly bolded to me.

Zoomed so text is very small - 67%
<img width="221" alt="Screen Shot 2020-11-27 at 9 03 24 AM" src="https://user-images.githubusercontent.com/5558419/100462250-9a2c8e80-308f-11eb-8039-b6e4043e17ff.png">

Slightly larger - 90%
<img width="291" alt="Screen Shot 2020-11-27 at 9 07 27 AM" src="https://user-images.githubusercontent.com/5558419/100462534-07d8ba80-3090-11eb-8211-c43faa9467e2.png">


Slightly larger - 110%
<img width="295" alt="Screen Shot 2020-11-27 at 9 04 00 AM" src="https://user-images.githubusercontent.com/5558419/100462303-af092200-308f-11eb-841c-9ebfb6f2d383.png">

**Comment by unode** [comment]
We could perhaps try other fonts.
Compared for instance with the **bold** here in GitHub, all the screenshots above have a rather light style, regardless of zoom factor.

**Comment by tobyhodges** [comment]
I think this is becoming an issue to raise over on the lesson template repository.

**Comment by unode** [comment]
I was thinking the same... would flag it under accessibility.

**Comment by tobyhodges** [comment]
perhaps make a comment on this thread? https://github.com/carpentries/carpentries-theme/issues/2
