### ISSUE TITLE
Draft_02_markdown

### ISSUE THREAD

**Issue by JulianKarlBauer** [carpentries-incubator/jekyll-pages-novice#2]
This is a dummy issue mimicking an empty Gitlab-merge-request and serving as a place to talk.

**Comment by JulianKarlBauer** [comment]
Participants must render their markdown.
@tobyhodges Which renderer do we recommend?

- Github file / Issue / ...
- A browser version?
- A simple local viewer?

**Comment by tobyhodges** [comment]
That's a great question! My first thought was to use HackMD/The Carpentries' CodiMD platform, but I think that will make things more complicated in the long run, because I'd like the learners to have files saved locally by the end of this episode. (So that they can then initialise version control on the project.)

So I guess a local viewer is the next best thing. I like Atom with the Markdown Preview plugin enabled, but that's not the easiest to set up. Maybe ghostwriter (Linux/Windows) and MacDown (OSX)? 

This is a point for further discussion at our next meeting, in case the other contributors have a preference based on experience.

**Comment by JulianKarlBauer** [comment]
Inspiration
- [R for Reproducible Scientific Analysis](https://swcarpentry.github.io/r-novice-gapminder/15-knitr-markdown/#markdown)
but I definitely want to improve the challenge...

**Comment by tobyhodges** [comment]
The other day I mentioned a "reverse-engineering" exercise, where the learner is given an image of some rendered text and asked to write the equivalent Markdown that produced it. I can also imagine a (perhaps optional) extension to this exercise, where the learner is shown some HTML and asked to write the equivalent Markdown. I say _perhaps optional_ because I don't think we should require that learners have prior knowledge of HTML in order to follow the lesson.

**Comment by JulianKarlBauer** [comment]
> That's a great question! My first thought was to use HackMD/The Carpentries' CodiMD platform, but I think that will make things more complicated in the long run, because I'd like the learners to have files saved locally by the end of this episode. (So that they can then initialise version control on the project.)
> 
> So I guess a local viewer is the next best thing. I like Atom with the Markdown Preview plugin enabled, but that's not the easiest to set up. Maybe ghostwriter (Linux/Windows) and MacDown (OSX)?
> 
> This is a point for further discussion at our next meeting, in case the other contributors have a preference based on experience.

Just in case we decided starting with an online-Editor for the first steps with markdown, one alternative to hackmd would be

[jbt-markdown-editor](http://jbt.github.io/markdown-editor/) from [repo](https://github.com/markdown-it/markdown-it).

This editor
- starts with a nearly blank document also after a refresh.
- opens and saves local files
- is quite minimal
