### ISSUE TITLE
Running a pilot workshop

### ISSUE THREAD

**Issue by apandas** [carpentries-incubator/jekyll-pages-novice#271]
Running two workshops at University of California, Santa Barbara:

- [2022 January 28](https://ucsbcarpentry.github.io/2022-01-28-ucsb-webpub-online/)

- [2022 January 31](https://ucsbcarpentry.github.io/2022-01-31-ucsb-webpub-online/)

**Comment by tobyhodges** [comment]
Great to hear that, @apandas. We'll be delighted to receive any feedback you have on the lesson. If you have any questions for us before the workshops take place, feel free to ask here or on [our Slack channel](https://swcarpentry.slack.com/archives/C0186GK56UC).

**Comment by jonjab** [comment]
We had a great time doing this lesson in 3 hours.

We needed more time. We think 4 hours would be adequate. Most of what we cut out involved the roster of lab mates and the named-entity links ( links.md )

Suggestions:

- be a little meta and show how the lesson repo itself depends on a links.md file
- double down on one of the examples (lab staff OR blog) and lost the second.

After includes, it seems the blog example that showcases the collections function is the highlight of the lesson. Is a blog the best example? Should the metaphor of a 'group website' be extended, and you can call the collection the group's newsletter. Or lab diary?

I am thinking about doubling down on the surgeon's diary

Layout inheritance is another aspect that could be more emphasized in the script. default, homepage, blogpost are the three you wind up with in the lesson. We propose moving the blog / newsletter / whatever to its own page, to emphasize that there are 3 layouts that all descend from default.

We will try to circle back and submit individual issues.

**Comment by tobyhodges** [comment]
Thank you very much for the feedback so far @jonjab! We are very glad to hear that you enjoyed teaching the lesson 😄 Your suggestions so far have been noted, and we would love it if you would open individual issues for the points you have mentioned already, and anything else that you noted down and/or would like to report.

We are interested in any and all feedback you have, but particularly in anything about [the final wrap-up exercises, customising a theme](https://carpentries-incubator.github.io/jekyll-pages-novice/wrap-up/index.html) - that section was added since the last time we taught the lesson and we are keen to hear how well it fits.
